[build]
  command = "curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 9.0.101 && export PATH=\"$HOME/.dotnet:$PATH\" && dotnet publish -c Release -o output"
  publish = "output/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200